Feat/viewer components
Geode-solutions/Vease pull request #80
Opened 2024-12-02 16:31 UTC by JulienChampagnol

2024-12-02 19:10 UTC, BotellaA commented on assets/viewer_svgs/block.svg
a voir si il faut deja tout ajouter

2024-12-02 19:10 UTC, BotellaA commented on components/Viewer/ContextualMenuItem.vue
c'est pas dans OGW Front ca ?

2024-12-02 19:10 UTC, BotellaA commented on components/Viewer/Surface/Color.vue
> +            ref="action"
utile cette ref?

2024-12-02 19:10 UTC, BotellaA commented on components/Viewer/Surface/Color.vue
> +watch(select, (value) => {
a partir de là c'est l'ancien code ?

2024-12-11 08:08 UTC, BotellaA commented on components/ContextMenu.vue
> +    <div
@SpliiT pour quelle raison on ne peut pas supprimer cette div ?

2024-12-11 08:08 UTC, BotellaA commented on components/ContextMenu.vue
> +        v-bind="{
si on utilise que itemProps, est-ce qu'on peut le passer directement sans le v-bind ?

2024-12-11 08:08 UTC, BotellaA commented on components/ContextMenu.vue
> +        :style="getItemStyle(index, menu_items.length)"
menu_items.length est souvent utilisé, faut-il faire un computed de ca et s'en servir ?

2024-12-11 08:08 UTC, BotellaA commented on components/TreeObject.vue
> +    style="
@SpliiT  peut-on mettre le style de cette div dans le container et la supprimer ?

2024-12-11 08:08 UTC, BotellaA commented on components/TreeObject.vue
>  const { selection } = toRefs(treeviewStore);
torefs ou storetorefs ? je ne suis pas sur qu'on change la valeur de la selection dans le store directement

2024-12-11 08:08 UTC, BotellaA commented on pages/index.vue
> +watch(display_menu, (value) => {
plusieurs watcher à supprimer ?

2024-12-11 08:08 UTC, BotellaA commented on pages/index.vue
> +  const container = document.querySelector(".v-card");
@SpliiT  non il faut mieux utiliser une ref vers le template, https://vuejs.org/api/composition-api-helpers.html#usetemplateref

2024-12-11 08:08 UTC, BotellaA commented on pages/index.vue
> +  console.log("containerWidth", containerWidth.value, containerHeight.value);
est-ce que ca c'est pas la responsabilité du ContextMenu? Genre on lui passe un container pour lui dire dans que viewport il doit s'afficher et il se débrouille pour trouver le reste ?

pour le moment, on peut laisser comme ca, je ne suis pas sur de ma remarque c'est plus une question ouverte

2024-12-11 08:08 UTC, BotellaA commented on components/ContextMenuItem.vue
> +
formatage

2024-12-11 08:08 UTC, BotellaA commented on components/ContextMenuItem.vue
> +  <div class="menu-item" :style="props.itemStyle">
est-ce que class et style s'applique sur toute la div ou que sur le bouton ?
est-ce qu'on peut mettre des class/style sur une balise template?

2024-12-11 08:08 UTC, BotellaA commented on components/ContextMenuItem.vue
> +.clickable-area {
a supprimer ?

2024-12-11 08:08 UTC, BotellaA commented on components/Viewer/EdgedCurve/Edges/Color.vue
> +        width="35"
ca c'est vraiment moche, on va s'en mordre les doigts tres vite. quid de changer ContextMenuItem et de ne laisser que le slot des options et de transformer tooltip et btn en props ? tooltip serait un string et btn serait le composant image ou le string path vers l'image ? on pourrait remonter le v-img dans ContextMenuItem et set une seule fois sa size

2024-12-11 08:08 UTC, BotellaA commented on components/Viewer/Generic/Mesh/Edges/Color.vue
> +            </template>
on pourrait aussi faire un composant séparé comme tu as fait pour VertexAttributes

2024-12-11 08:08 UTC, BotellaA commented on components/Viewer/Generic/Mesh/Edges/Color.vue
> +      return "";
```suggestion
      return "Select a coloring";
```
ou un truc du genre ?

2024-12-11 08:08 UTC, BotellaA commented on components/Viewer/Generic/Mesh/Points/Color.vue
> +            <VertexAttributeSelector v-if="select === styles[1]" @update_value="vertexAttributeName = $event"/>
pk utiliser un @update_value plutot plutot qu'un v-model?

2024-12-11 08:08 UTC, BotellaA commented on electron/main.js
> +// import installExtension, {
nettoyer

2024-12-11 08:08 UTC, BotellaA commented on electron/main.js
> +  // VUEJS_DEVTOOLS,
nettoyer

2024-12-11 10:56 UTC, SpliiT commented on components/ContextMenu.vue
> +    <div
elle gère la taille globale du menu et le positionnement des items dans le menu

2024-12-11 15:59 UTC, SpliiT commented on components/ContextMenuItem.vue
> +  <div class="menu-item" :style="props.itemStyle">
Elle s'applique sur toute la div. On ne peut pas mettre de class ou de style sur la balise template

2024-12-20 21:06 UTC, BotellaA requested changes

2024-12-20 21:06 UTC, BotellaA commented on components/ConstantColorPicker.vue
> +const el = ref(null);
Non, il y'a un useTemplateRef il me semble.
A changer partout

2024-12-20 21:06 UTC, BotellaA commented on components/ConstantColorPicker.vue
> +const { pressed } = useMousePressed({ target: el });
J'ai l'impression que tu vas t'en servir plusieurs fois de regarder le pressed + watcher + update d'un model. Est-ce que ça serait pas un composable genre useUpdateWhenMouseRelease qui prendrait un élément du dom, la valeur à watch et celle à update ?

2024-12-20 21:06 UTC, BotellaA commented on components/TreeObject.vue
> -          item-value="id"
C'est quoi ces deux props en moins ?

2025-01-03 11:27 UTC, BotellaA approved these changes

2025-01-03 11:54 UTC, merged

2025-01-03 11:54 UTC, JulienChampagnol commented
:tada: This PR is included in version 1.0.0-rc.1 :tada:

The release is available on [GitHub release](https://github.com/Geode-solutions/Vease/releases/tag/v1.0.0-rc.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-01-03 13:32 UTC, JulienChampagnol commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Geode-solutions/Vease/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: